### ISSUE TITLE
(g/open) overrides the former g/*graph*

### ISSUE THREAD

**Issue by ghost** [play-co/hermes#35]
Is this by design ?
Or maybe I'm not even getting this right...

but for example if I do,

``` clojure
(def a (g/open))
(def b (g/open))
(.shutdown b)
;at this point I'm stuck with the last graph opened 
=> (= g/*graph* b)
true
=> (= g/*graph* a)
false
```

There doesn't seem to be a way to switch back the `g/*graph*` to a, unless maybe g/open would use bindings, even so they are only valid for the current thread (not sure if this is relevant, maybe if hermes uses multiple threads it is, or the tests run on parallel? ever?)

I'm sure I can find a way around this, I probably shouldn't have opened this issue. EDIT: I'll just wrap the calls in functions that take a graph and use binding inside. EDIT2: just realized bindings are useless since the var-root is being changed, so I must find another way.

I was also going to ask why use a `*graph*` and not just pass it around to methods ? other than optimized for ie. speed maybe ? or hassle free?

Thank you.

**Comment by zmaril** [comment]
Typically, one does not change graphs often in an application. We considered passing graphs around to functions and it just didn't make sense to us. If you really are working with multiple graphs often, try looking into `hermes.core/with-graph` and see if that does anything for you. It rebinds `*graph*` to whatever graph you pass in and executes whatever you want with that new graph. 

I'm closing this because I don't think we want to support working with multiple graphs beyond `with-graph`. I invite you to find a compelling use case though that `with-graph` doesn't support and I'd happily reconsider this position.

**Comment by ghost** [comment]
You're right that should do the trick, though I got stuck into wanting to make sure none of hermes' code modify the `*graph*` and that failed since `g/open` uses `alter-var-root`, but I guess I could live without imposing that constraint on the code that I wrap around hermes.
 Thank you.

EDIT: now I see `*graph*` as being `*last-opened-graph*`
EDIT2: I'm thinking, if I'm using 2 libraries in my project and each of them use hermes (but my project doesn't, or my project does and one of the libs it's using also does) then `g/open` executed in each of our projects would do some serious intermingling. So hmm... i dno, I'll think about how to avoid this. EDIT3: <del>or do each of them get a different copy? of the namespace and `*graph*`</del> ? ok looks like they see the same `*graph*`

**Comment by ghost** [comment]
ok, EDIT2 above would be my only reason I guess.

Considering this, are there any plans on changing this? it's ok with me if not, I just need to know if I need to plan around this or wait for the change(if any) then plan/code
EDIT: actually, it's much more sensible for me to assume this won't be changed in hermes and I should code around it somehow, that is if EDIT2 above is true (according to my asking on irc it would be true)
